version: '3.3'

services:

  php7fpm:
   build: ./build/php7fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./server/php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"

  lb1:
    image: haproxy:1.7.9
    container_name: docker-haproxy
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./balance/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
      - "8000:8000"

  sv1:
    image: nginx:1.12.2-alpine
    container_name: docker-sv1
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./server/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "8001:80"

  sv2:
    image: nginx:1.12.2-alpine
    container_name: docker-sv2
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./server/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "8002:80"