version: '3.4'

services:

  php7fpm:
   build: ./build/php7fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_PORT=9000
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf.d/php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - frontend_network

  lb1:
    image: haproxy:1.8.2-alpine
    container_name: docker-haproxy
    restart: always
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_PORT=8000
      - TERM=xterm
    volumes:
      - ./balance/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - frontend_network

  sv1:
    image: nginx:1.12.2-alpine
    container_name: docker-sv1
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_PORT=8001
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "8001:80"
    networks:
      - frontend_network

  sv2:
    image: nginx:1.12.2-alpine
    container_name: docker-sv2
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_PORT=8002
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "8002:80"
    networks:
      - frontend_network

networks:
  frontend_network: