version: '3.3'

services:

  php7fpm:
    image: php:7.1.11-fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    volumes:
      - ./php7-ini/php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"