version: '3'

services:

  php7fpm:
    image: php:7.2.10-fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_PORT=9000
      - TERM=xterm
    volumes:
      - ./php7-ini/php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - frontend_network

networks:
  frontend_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24