version: '3.3'

services:

  php7fpm:
    build: ./build/php7fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/php7.conf/php7.ini/php7-upload.ini:/usr/local/etc/php/php.ini
      - ./config/php7.conf/php7.ini/20-mongodb.ini:/usr/local/etc/php/conf.d/20-mongodb.ini
      - ./config/php7.conf/php7.ini/20-phalcon.ini:/usr/local/etc/php/conf.d/20-phalcon.ini
      - ./config/php7.conf/php7.ext/mongodb-v1.2.9.so:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/mongodb-v1.2.9.so
      - ./config/php7.conf/php7.ext/phalcon-v3.2.1.so:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/phalcon-v3.2.1.so
    ports:
      - "9000:9000"
    networks:
      - frontend_network

  mariadb:
    image: mariadb:10.3.0
    container_name: docker-mariadb
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
#     - MYSQL_DATABASE=db_admin
#     - MYSQL_USER=admin
#     - MYSQL_PASSWORD=123456
      - TERM=xterm
    volumes:
      - ./backup/mariadb/backup:/backup
#     - ./backup/mariadb/data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: mysqld --innodb-buffer-pool-size=20M
    networks:
      - frontend_network

  mongodb:
    image: mongo:3.5.11
    container_name: docker-mongo
    restart: always
    environment:
      - AUTH=no
      - TERM=xterm
    volumes:
      - ./backup/mongodb/backup:/backup
#     - ./backup/mongodb/data:/var/lib/mysql
    ports:
      - "27017:27017"
    command: mongod --smallfiles
#   command: mongod --smallfiles --auth
    networks:
      - frontend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.3-1
    container_name: docker-phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
#     - PMA_USER=admin
#     - PMA_PASSWORD=123456
      - TERM=xterm
    links:
      - "mariadb:mariadb"
    ports:
      - "8080:80"
    networks:
      - frontend_network

  nginx:
    image: nginx:1.12.1-alpine
    container_name: docker-nginx
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/conf.d/vhosts:/etc/nginx/conf.d/vhosts
      - ./config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/conf.d/nginx.conf:/etc/nginx/nginx.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend_network

networks:
  frontend_network: