version: '3.4'

services:

  php7fpm:
    image: php:7.2.2-fpm
    container_name: docker-php7fpm
    restart: always
    environment:
      - VIRTUAL_PORT=9000
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./php7-ini/php7.ini:/usr/local/etc/php/php.ini
      - ./php7-ini/phalcon.ini:/usr/local/etc/php/conf.d/phalcon.ini
      - ./php7-ini/mongodb.ini:/usr/local/etc/php/conf.d/mongodb.ini
      - ./php7-ext/phalcon-v3.3.1.so:/usr/local/lib/php/extensions/no-debug-non-zts-20170718/phalcon-v3.3.1.so
      - ./php7-ext/mongodb-v1.3.4.so:/usr/local/lib/php/extensions/no-debug-non-zts-20170718/mongodb-v1.3.4.so
    ports:
      - "9000:9000"
    networks:
      - frontend_network

  nginx:
    image: nginx:1.12.2-alpine
    container_name: docker-nginx
    restart: always
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
      - VIRTUAL_PORT=443
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - NGINX_PORT=443
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend_network

networks:
  frontend_network: