version: '3.3'

services:

  php7fpm:
    image: php:7.2.0-fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
      - ./php7-ini/php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.12.2-alpine
    container_name: docker-nginx
    working_dir: /usr/share/nginx/html
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "80:80"
      - "443:443"