version: '3'

services:

  mysql:
    image: mysql:5.7.23
    container_name: docker-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
#     - MYSQL_DATABASE=db_admin
#     - MYSQL_USER=admin
#     - MYSQL_PASSWORD=123456
      - VIRTUAL_PORT=3306
      - TERM=xterm
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - database_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.3
    container_name: docker-phpmyadmin
    restart: always
    environment:
      - VIRTUAL_PORT=8080
      - PMA_HOST=mysql
      - TERM=xterm
#     - PMA_USER=admin
#     - PMA_PASSWORD=123456
    links:
      - "mysql:mysql"
    ports:
      - "8080:80"
    networks:
      - database_network

networks:
  database_network:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24