version: '3.4'

services:

  nginx:
    image: nginx:1.12.2-alpine
    container_name: docker-nginx
    working_dir: /usr/share/nginx/html    
    restart: always
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
      - VIRTUAL_PORT=443
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - NGINX_PORT=443
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf   
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend_network

networks:
  frontend_network: