version: "3"

services:

# ======================================================================
# Database | 7000
# ======================================================================

  maria:
    image: mariadb:10.3.9
    container_name: wordpress-maria
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=F8hflg9Hx@min61++
      - VIRTUAL_PORT=3306
      - TERM=xterm
    volumes:
      - ./database/backup/sql:/backup
      - ./database/sql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - database_network
  
  mongo:
    image: mongo:4.1.3
    container_name: wordpress-mongo
    restart: always
    environment:
      - VIRTUAL_PORT=27017
      - TERM=xterm
      - AUTH=yes
    volumes:
      - ./database/backup/mongo:/backup
      - ./database/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - database_network
    command: mongod
  
  pma:
    depends_on:
      - maria
    image: phpmyadmin/phpmyadmin:4.8.3
    container_name: wordpress-pma
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=F8hflg9Hx@min61++
      - VIRTUAL_PORT=8080
      - TERM=xterm
    links:
      - "sql:mariadb"
    ports:
      - "8080:80"
    networks:
      - database_network

# ======================================================================
# PHP7 + Wordpress | 9000
# ======================================================================

  wordress:
    depends_on:
      - maria
    build: ./build
    container_name: wordpress-php7fpm1
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_PORT=9001
      - WORDPRESS_DB_HOST=maria:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=F8hflg9Hx@min61++
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf.d/php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9001:9000"
    links:
      - "mongo:mongo"
      - "sql:mysql"
    networks:
      - frontend_network
      - database_network

# ======================================================================
# Web Server | 8000
# ======================================================================

  main:
    image: nginx:1.15.6-alpine
    container_name: wordpress-main
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
#     - VIRTUAL_HOST=codestep.local
      - VIRTUAL_PORT=8100
#     - NGINX_HOST=codestep.local
      - NGINX_PORT=80
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "8100:80"
    networks:
      - frontend_network
      - database_network

networks:
  frontend_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
  database_network:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24