version: '3.3'

services:

  mariadb:
    image: mariadb:10.2.11
    container_name: docker-mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
#     - MYSQL_DATABASE=db_admin
#     - MYSQL_USER=admin
#     - MYSQL_PASSWORD=123456
      - TERM=xterm
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.7-1
    container_name: docker-phpmyadmin
    restart: always
    environment:
      - TERM=xterm
      - PMA_HOST=mariadb
#     - PMA_USER=root
#     - PMA_PASSWORD=123456
    links:
      - "mariadb:mariadb"
    ports:
      - "8080:80"