version: '3'

services:

  redis:
    image: redis:4.0.11-alpine
    container_name: docker-redis
    restart: always
    environment:
      - VIRTUAL_PORT=6379
      - TERM=xterm
    volumes:
      - ./data:/data
      - ./conf.d/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - "6379:6379"
    networks:
      - database_network

networks:
  frontend_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24