version: '3.3'

services:

  redis:
    image: redis:4.0.2
    container_name: docker-redis
    restart: always
    volumes:
      - ./data:/data
      - ./conf.d/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - "6379:6379"