version: '3.4'

services:

  node:
    build: .
    container_name: docker-node
    restart: always
    environment:
      - VIRTUAL_PORT=8000
      - TERM=xterm
#    volumes:
#      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - frontend_network

networks:
  frontend_network: